### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by sroberson** [jamiew/ohmfork-autoclaim#7]
How does this work?  I'm trying this but it fails:

```▶ yarn run klimadao:stats
yarn run v1.22.15
$ yarn hardhat run --network polygon scripts/klimadao/stats.ts 
$ /Users/meebo/work/personal/ohmfork-autoclaim/node_modules/.bin/hardhat run --network polygon scripts/klimadao/stats.ts
HardhatError: HH700: Artifact for contract "KlimaToken" not found.
    at Artifacts._getArtifactPathFromFiles (/Users/meebo/work/personal/ohmfork-autoclaim/node_modules/hardhat/src/internal/artifacts.ts:391:13)
    at Artifacts._getArtifactPath (/Users/meebo/work/personal/ohmfork-autoclaim/node_modules/hardhat/src/internal/artifacts.ts:316:17)
    at Artifacts.readArtifact (/Users/meebo/work/personal/ohmfork-autoclaim/node_modules/hardhat/src/internal/artifacts.ts:49:26)
    at getContractAt (/Users/meebo/work/personal/ohmfork-autoclaim/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:271:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jamiew** [comment]
Ah my bad, looks like a bad merge. Will revisit
